### ISSUE TITLE
Agent Chat App does not support blocking mode

### ISSUE THREAD

**Issue by baiyi-os** [MAyang38/dify-on-dingding-go#1]
我在dify商创建了一个Agent，使用咱们的工具，返回400
No conversation ID found for user: $:LWCP_v1:$Sa9pwolIG+FnugDb9s45PA==
API request failed with status: 400, response: {"code": "invalid_param", "message": "Agent Chat App does not support blocking mode", "status": 400}
是否可以出一个视频教程

**Comment by MAyang38** [comment]
你好 我复现了这个问题， 需要把.env 文件里的Output_Type由Text改成**Stream** ，使用流式输出，目前agent是不支持block模式，会超时。
