### ISSUE TITLE
鉴权失败

### ISSUE THREAD

**Issue by altxf4** [MAyang38/dify-on-dingding-go#2]
在docker desktop运行提示这个错误
panic: {"requestid":"AB45C224-AE3D-7BAD-8F5E-B7746FA16F3C","code":"authFailed","message":"鉴权失败"}

2024-08-07 16:15:45 No keywords found in environment
2024-08-07 16:15:45 Deleted 0 keys
2024-08-07 16:15:46 panic: {"requestid":"AB45C224-AE3D-7BAD-8F5E-B7746FA16F3C","code":"authFailed","message":"鉴权失败"}
2024-08-07 16:15:46 
2024-08-07 16:15:46 goroutine 1 [running]:
2024-08-07 16:15:46 ding/bot/dingtalk.StartDingRobot()
2024-08-07 16:15:46     /app/bot/dingtalk/ding.go:56 +0x190
2024-08-07 16:15:46 main.main()
2024-08-07 16:15:46     /app/main.go:36 +0xeb
请问下，是什么问题啊

**Comment by MAyang38** [comment]
你将配置文件.env 修改为自己的钉钉机器人的id 和secret了吗

**Comment by altxf4** [comment]
![Dingtalk_20240807165255](https://github.com/user-attachments/assets/c5338731-3271-4f89-b9e7-9d7fdcbf3575)
这个是我的环境配置

**Comment by altxf4** [comment]
这个鉴权是redis，dify ，还是钉钉啊？dify我用的是本地，这个行吗？

**Comment by MAyang38** [comment]
这个鉴权应该是钉钉

可爱小羊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MAyang38/dify-on-dingding-go"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月7日(星期三) 下午4:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MAyang38/dify-on-dingding-go] 鉴权失败 (Issue #2)





 
这个鉴权是redis，dify ，还是钉钉啊？dify我用的是本地，这个行吗？

**Comment by MAyang38** [comment]
这个鉴权应该是钉钉，你这个panic是在连接钉钉的时候失败的 。

可爱小羊
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "MAyang38/dify-on-dingding-go"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月7日(星期三) 下午4:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MAyang38/dify-on-dingding-go] 鉴权失败 (Issue #2)





 
这个鉴权是redis，dify ，还是钉钉啊？dify我用的是本地，这个行吗？

**Comment by MAyang38** [comment]
配置是没什么问题， 你的机器人应用发布了吗  目前来看是这个机器人的问题

**Comment by altxf4** [comment]
补充下，我本地的结果是这样的，代表成功吗？
![image](https://github.com/user-attachments/assets/f291c315-3620-41a4-b791-48ff60283b7e)

**Comment by MAyang38** [comment]
你再给这个机器人发消息 他就能调用dify的工作流回消息了

**Comment by altxf4** [comment]
> 上面那个是在云服务器里的吗

本地运行是没有问题，钉钉机器人也可以调用。但是在Docker里面就是鉴权失败。

**Comment by MAyang38** [comment]
> > 上面那个是在云服务器里的吗
> 
> 本地运行是没有问题，钉钉机器人也可以调用。但是在Docker里面就是鉴权失败。

我这里在docker 里也没问题， 把镜像都删了重新docker-compose up -d 试试呢

**Comment by altxf4** [comment]
> > > 上面那个是在云服务器里的吗
> > 
> > 
> > 本地运行是没有问题，钉钉机器人也可以调用。但是在Docker里面就是鉴权失败。
> 
> 我这里在docker 里也没问题， 把镜像都删了重新docker-compose up -d 试试呢

今天又重新试了下，环境全是本地一台机子。本地用vs 调试，钉钉可用。换到Docker 里面就是失败，一会儿是
panic: {"requestid":"2DDCBD56-945E-7ADA-9AF4-5D5BC44A8C7E","code":"authFailed","message":"鉴权失败"}；
一会又变成这个失败panic: Post "https://api.dingtalk.com/v1.0/gateway/connections/open": dial tcp [2401:b180:2000:70::e]:443: connect: network is unreachable

**Comment by altxf4** [comment]
用的是钉钉新版的API

**Comment by MAyang38** [comment]
> > > > 上面那个是在云服务器里的吗
> > > 
> > > 
> > > 本地运行是没有问题，钉钉机器人也可以调用。但是在Docker里面就是鉴权失败。
> > 
> > 
> > 我这里在docker 里也没问题， 把镜像都删了重新docker-compose up -d 试试呢
> 
> 今天又重新试了下，环境全是本地一台机子。本地用vs 调试，钉钉可用。换到Docker 里面就是失败，一会儿是 panic: {"requestid":"2DDCBD56-945E-7ADA-9AF4-5D5BC44A8C7E","code":"authFailed","message":"鉴权失败"}； 一会又变成这个失败panic: Post "https://api.dingtalk.com/v1.0/gateway/connections/open": dial tcp [2401:b180:2000:70::e]:443: connect: network is unreachable

这看起来像你的docker 网络有问题啊

**Comment by altxf4** [comment]
> > > > > 上面那个是在云服务器里的吗
> > > > 
> > > > 
> > > > 本地运行是没有问题，钉钉机器人也可以调用。但是在Docker里面就是鉴权失败。
> > > 
> > > 
> > > 我这里在docker 里也没问题， 把镜像都删了重新docker-compose up -d 试试呢
> > 
> > 
> > 今天又重新试了下，环境全是本地一台机子。本地用vs 调试，钉钉可用。换到Docker 里面就是失败，一会儿是 panic: {"requestid":"2DDCBD56-945E-7ADA-9AF4-5D5BC44A8C7E","code":"authFailed","message":"鉴权失败"}； 一会又变成这个失败panic: Post "https://api.dingtalk.com/v1.0/gateway/connections/open": dial tcp [2401:b180:2000:70::e]:443: connect: network is unreachable
> 
> 这看起来像你的docker 网络有问题啊

我用的是Docker Desktop4.30，怎么查看网络设置呢。困扰了我1天了，本地调试就行，Docker里面就不行，我的代码环境都重新搞了一次。

**Comment by MAyang38** [comment]
> > > > > > 上面那个是在云服务器里的吗
> > > > > 
> > > > > 
> > > > > 本地运行是没有问题，钉钉机器人也可以调用。但是在Docker里面就是鉴权失败。
> > > > 
> > > > 
> > > > 我这里在docker 里也没问题， 把镜像都删了重新docker-compose up -d 试试呢
> > > 
> > > 
> > > 今天又重新试了下，环境全是本地一台机子。本地用vs 调试，钉钉可用。换到Docker 里面就是失败，一会儿是 panic: {"requestid":"2DDCBD56-945E-7ADA-9AF4-5D5BC44A8C7E","code":"authFailed","message":"鉴权失败"}； 一会又变成这个失败panic: Post "https://api.dingtalk.com/v1.0/gateway/connections/open": dial tcp [2401:b180:2000:70::e]:443: connect: network is unreachable
> > 
> > 
> > 这看起来像你的docker 网络有问题啊
> 
> 我用的是Docker Desktop4.30，怎么查看网络设置呢。困扰了我1天了，本地调试就行，Docker里面就不行，我的代码环境都重新搞了一次。

你的容器里有网吗 可以连通外界吗   这个具体的 我也不清除  没遇过docker 这种问题

**Comment by altxf4** [comment]
> > > > > > > 上面那个是在云服务器里的吗
> > > > > > 
> > > > > > 
> > > > > > 本地运行是没有问题，钉钉机器人也可以调用。但是在Docker里面就是鉴权失败。
> > > > > 
> > > > > 
> > > > > 我这里在docker 里也没问题， 把镜像都删了重新docker-compose up -d 试试呢
> > > > 
> > > > 
> > > > 今天又重新试了下，环境全是本地一台机子。本地用vs 调试，钉钉可用。换到Docker 里面就是失败，一会儿是 panic: {"requestid":"2DDCBD56-945E-7ADA-9AF4-5D5BC44A8C7E","code":"authFailed","message":"鉴权失败"}； 一会又变成这个失败panic: Post "https://api.dingtalk.com/v1.0/gateway/connections/open": dial tcp [2401:b180:2000:70::e]:443: connect: network is unreachable
> > > 
> > > 
> > > 这看起来像你的docker 网络有问题啊
> > 
> > 
> > 我用的是Docker Desktop4.30，怎么查看网络设置呢。困扰了我1天了，本地调试就行，Docker里面就不行，我的代码环境都重新搞了一次。
> 
> 你的容器里有网吗 可以连通外界吗 这个具体的 我也不清除 没遇过docker 这种问题

终于解决了， docker desktop网络问题。

**Comment by Kennytian** [comment]
还有一个经验跟大家分享，香港的aws服务器好像连不上 https://api.dingtalk.com，也报鉴权失败，但换腾讯云就没问题。

但也有可能是我的「香港aws」没有配置好
