### ISSUE TITLE
多问钉钉机器人几次问题就报这个错

### ISSUE THREAD

**Issue by altxf4** [MAyang38/dify-on-dingding-go#3]
Error updating DingTalk card: SDKError:
   StatusCode: 400
   Code: system.error
   Message: code: 400, 未知的系统错误 request id: C5E5828E-7F1F-75AF-86D0-D1945398799A
   Data: {"code":"system.error","message":"未知的系统错误","requestid":"C5E5828E-7F1F-75AF-86D0-D1945398799A","statusCode":400}

**Comment by MAyang38** [comment]
> Error updating DingTalk card: SDKError: StatusCode: 400 Code: system.error Message: code: 400, 未知的系统错误 request id: C5E5828E-7F1F-75AF-86D0-D1945398799A Data: {"code":"system.error","message":"未知的系统错误","requestid":"C5E5828E-7F1F-75AF-86D0-D1945398799A","statusCode":400}

这是钉钉内部的错误了   这个我不清楚如何解决，    影响回答吗

**Comment by altxf4** [comment]
> > Error updating DingTalk card: SDKError: StatusCode: 400 Code: system.error Message: code: 400, 未知的系统错误 request id: C5E5828E-7F1F-75AF-86D0-D1945398799A Data: {"code":"system.error","message":"未知的系统错误","requestid":"C5E5828E-7F1F-75AF-86D0-D1945398799A","statusCode":400}
> 
> 这是钉钉内部的错误了 这个我不清楚如何解决， 影响回答吗

这个是AI接口返回超时，造成的。
